version: "3"
services:
  crudapp:
    image: crudapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
  json-server:
    container_name: json-server-container
    image: json-server-image
    build: ./db
    environment:
      - DB_HOST=json-server
    ports:
      - "3000:3000"
    volumes:
      - ./db/db.json:/data/db.json
    command: json-server --watch /data/db.json --host 0.0.0.0
volumes:
  node_modules:
